/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbdescrambler_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1b054cd08803121f19cb3e29633c8d51)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2rx/bbdescrambler_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bbdescrambler_bb_pydoc.h>

void bind_bbdescrambler_bb(py::module& m)
{

    using bbdescrambler_bb = ::gr::dvbs2rx::bbdescrambler_bb;


    py::class_<bbdescrambler_bb,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<bbdescrambler_bb>>(
        m, "bbdescrambler_bb", D(bbdescrambler_bb))

        .def(py::init(&bbdescrambler_bb::make),
             py::arg("standard"),
             py::arg("framesize"),
             py::arg("rate"),
             D(bbdescrambler_bb, make))


        ;
}
