/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bch_decoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9ce4730363a1d64d74e5458847ad1f1a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2rx/bch_decoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bch_decoder_bb_pydoc.h>

void bind_bch_decoder_bb(py::module& m)
{

    using bch_decoder_bb = ::gr::dvbs2rx::bch_decoder_bb;


    py::class_<bch_decoder_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<bch_decoder_bb>>(m, "bch_decoder_bb", D(bch_decoder_bb))

        .def(py::init(&bch_decoder_bb::make),
             py::arg("standard"),
             py::arg("framesize"),
             py::arg("rate"),
             py::arg("outputmode"),
             py::arg("debug_level") = 0,
             D(bch_decoder_bb, make))

        .def("get_frame_count",
             &bch_decoder_bb::get_frame_count,
             D(bch_decoder_bb, get_frame_count))

        .def("get_error_count",
             &bch_decoder_bb::get_error_count,
             D(bch_decoder_bb, get_error_count))

        ;
}
