/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvb_params.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7234c68464518915c4003a1f9fe46756)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2rx/dvb_params.h>
// pydoc.h is automatically generated in the build directory
#include <dvb_params_pydoc.h>

void bind_dvb_params(py::module& m)
{

    using dvb_params = ::gr::dvbs2rx::dvb_params;


    py::class_<dvb_params, std::shared_ptr<dvb_params>>(m, "dvb_params", D(dvb_params))

        .def(py::init(&dvb_params::make),
             py::arg("standard"),
             py::arg("frame_size"),
             py::arg("code_rate"),
             py::arg("constellation"),
             py::arg("rolloff"),
             py::arg("pilots"),
             py::arg("vl_snr") = false,
             D(dvb_params, make))

        .def_readonly("standard", &dvb_params::standard)
        .def_readonly("framesize", &dvb_params::framesize)
        .def_readonly("rate", &dvb_params::rate)
        .def_readonly("constellation", &dvb_params::constellation)
        .def_readonly("rolloff", &dvb_params::rolloff)
        .def_readonly("pilots", &dvb_params::pilots)

        ;
}
