/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ldpc_decoder_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6600d4874aba2dd3820976811b5e2cee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2rx/ldpc_decoder_bb.h>
// pydoc.h is automatically generated in the build directory
#include <ldpc_decoder_bb_pydoc.h>

void bind_ldpc_decoder_bb(py::module& m)
{

    using ldpc_decoder_bb = ::gr::dvbs2rx::ldpc_decoder_bb;


    py::class_<ldpc_decoder_bb,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ldpc_decoder_bb>>(m, "ldpc_decoder_bb", D(ldpc_decoder_bb))

        .def(py::init(&ldpc_decoder_bb::make),
             py::arg("standard"),
             py::arg("framesize"),
             py::arg("rate"),
             py::arg("constellation"),
             py::arg("outputmode"),
             py::arg("infomode"),
             py::arg("max_trials"),
             py::arg("debug_level") = 0,
             D(ldpc_decoder_bb, make))

        .def("get_average_trials",
             &ldpc_decoder_bb::get_average_trials,
             D(ldpc_decoder_bb, get_average_trials))

        ;
}
