/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dvbs2rx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DVBS2RX_API_H
#define INCLUDED_DVBS2RX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dvbs2rx_EXPORTS
#define DVBS2RX_API __GR_ATTR_EXPORT
#else
#define DVBS2RX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DVBS2RX_API_H */
